### ISSUE TITLE
[BUG]: [csi-vxflexos]: `controller.yaml` template has unnecessary `nodeSelector` field under `spec.template.spec.affinity`

### ISSUE THREAD

**Issue by Waji-97** [dell/helm-charts#427]
**Describe the bug**
The `controller.yaml` template has an unknown field under `spec.template.spec.affinity` part of the latest csi-vxflexos Helm Chart. 

The exact `warning` message on `helm install`
```bash
 281201 warnings.go:70] unknown field "spec.template.spec.affinity.nodeSelector"
```

Upon investigation, found unnecessary `nodeSelector` field in line 174 of `controller.yaml`
```bash
    spec:
      affinity:
        nodeSelector:  ## ==> cause of the warning
        podAntiAffinity:
```

After removing the line and executing `helm install`, the warning message was gone. 

**Version of Helm and Kubernetes**:
- Kubernetes v1.26.13
- Helm v3.14.3

**Which chart**:
- csi-vxflexos

**How to reproduce it** (as minimally and precisely as possible):
Using `helm lint` doesn't show any failures. However, installing the chart using `helm install` will give us the above-mentioned warning message along-with a successful installation of the CSI driver.

**Anything else we need to know**:
The installation of the CSI driver itself doesn't get affected as the above is just a warning message, not an error. I am unsure if this should be considered as a "bug" but I felt like this should be updated over here as well.

**Comment by shaynafinocchiaro** [comment]
Closing issue as resolved. Please feel free to open another github issue for further issues. 
We also have github issues filed [here ](https://github.com/dell/csm/issues) as well. Thank you.
