### ISSUE TITLE
[BUG]: [karavi-observability]: Helm chart repository URL is incorrect in offline installer script

### ISSUE THREAD

**Issue by gallacher** [dell/helm-charts#52]
**Describe the bug**
The Helm chart repository URL is incorrect in offline installer script.  It needs to be changed to "https://dell.github.io/helm-charts"

**Version of Helm and Kubernetes**:
-Helm: 3.0
-Kubernetes: 1.18

**Which chart**:
karavi-observability

**What happened**:
Offline installer does not work correctly because of bad chart repo URL.

**What you expected to happen**:
The offline installer should work

**How to reproduce it** (as minimally and precisely as possible):
Run the offline install script, it will fail.

**Provide logs, errors/output**
N/A

**Anything else we need to know**:
N/A

**Comment by ioeicicdsvc** [comment]
link: 1677
