### ISSUE TITLE
[BUG]: [helm-charts]: Move Documentation to /docs

### ISSUE THREAD

**Issue by medegw01** [dell/helm-charts#56]
**Describe the bug**
For all other karavi projects which use our open source project template, documentation is stored in a folder called `docs`. For uniformity and to improve automation, maintainer.md, contributing.md, and others will be moved into a new folder called `docs`

**Version of Helm and Kubernetes**:
N/A

**Which chart**:
N/A

**What happened**:
 `docs` folder cannot be found

**What you expected to happen**:
I expect to see all the documentation in the `docs` folder and not in the root directory of the repo

**How to reproduce it** (as minimally and precisely as possible):
See the repo and compare to other karavi repos

**Provide logs, errors/output**
N/A

**Anything else we need to know**:
No

**Comment by ioeicicdsvc** [comment]
link: 1783
