### ISSUE TITLE
[BUG]: [chart name (if applicable)]: Test helm charts bug

### ISSUE THREAD

**Issue by tdawe** [dell/helm-charts#58]
**Describe the bug**

**Version of Helm and Kubernetes**:

**Which chart**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Provide logs, errors/output**

**Anything else we need to know**:

**Comment by ioeicicdsvc** [comment]
Unable to move issue to dell/karavi-topology2

**Comment by ioeicicdsvc** [comment]
This issue has moved to https://github.com/dell/karavi-topology/issues/77 because it is related to the project located at dell/karavi-topology
